auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html
exclude: [shower,themes]

default_theme: ribbon
default_lang: en
default_body_class: list

author:
    name: Matthew Wilson
    # url:  http://example.com/
    company:
        name: DCBPW 2013
        # url:  http://example.com/

fork_url: https://github.com/diakopter/jekyller
progress: true
